name: jkbella
favicon: null
layout_spectrum: 0.13485013507306576
typography_spectrum: 0.20620917691849172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9542743864003569
  lightness: 0.5341778937727213
  saturation: 0.24718232499435544
  rhythmicContrast: 0.750509828561917
purpose: []
